apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-xrayconnector
data:
  # Following function keys to protect your functions, are pre-generated and NEED TO BE REPLACED with new keys to prevent mis-use of the api!
  # When changing the keys, make sure to also adjust the key in the CronJob's ('xrayconnector-watchdog') url 
  # The keys are encoded in base64
  host.master: T210QWJpTVhlZ3pwZ0lPanBTWnA0LVB2UTE3QUw4NzVteTEtU1R3cGhnTVhBekZ1R2M4MzRnPT0=
  host.function.default: T0tuc01Ic2JUZGYtM0h0QnI5Z3dmUWR3UGQxejVjekJhRjFBSUJkek9BUkhBekZ1X0kyV1p3PT0=
  host.systemKey.default: TWpBUW9QbVFkQUJjbU9sOFBaeHpTWFdhN0lCX0l2OFpFZUkzbUFlM3EwekFBekZ1YUZKaUtnPT0=
  functions.terminateinstance.default: UGRhd2lkZE5zYk1ZcVJuNmx1RGxTYUJFVGg5QWJidm1PVElNVmxFenNDeThBekZ1TGdOd3VRPT0=
  functions.testping.default: azNvOFdqdG9laUVnZllQN2FVZGhkTmFmbFBvR21adUtrUHE1aDJNNG52TDJBekZ1QlFhWUhBPT0=
  functions.triggerperiodicapipoller.default: bWJPNnNmdkhic0dodGdZR3JUZ2R5b0VrRlpfTUxKYXhZV2s3SnQwTEJiVEpBekZ1S1BhNUFBPT0=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xrayconnector-function-keys-identity-svc-act
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xrayconnector-function-keys-identity-svc-act-functions-keys-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: xrayconnector-function-keys-identity-svc-act
---
apiVersion: v1
kind: Service
metadata:
  name: xrayconnector
spec:
  selector:
    app: xrayconnector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrayconnector
  labels:
    app: xrayconnector
spec:
  selector:
    matchLabels:
      app: xrayconnector
  template:
    metadata:
      labels:
        app: xrayconnector
    spec:
      containers:
      - name: xrayconnector
        image: <YOUR-REPOSITORY>/xrayconnector:latest
        env:
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-xrayconnector
        envFrom:
        - secretRef:
            name: connector-config
        readinessProbe:
          httpGet:
            path: /api/TestPing
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/TestPing
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
      serviceAccountName: xrayconnector-function-keys-identity-svc-act
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xrayconnector-poller
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  concurrencyPolicy: Replace  # Ensures only one job runs at a time
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - curl
            args:
            - "-X"
            - "POST"
            - "http://xrayconnector/api/PollXRayTraces?code=T210QWJpTVhlZ3pwZ0lPanBTWnA0LVB2UTE3QUw4NzVteTEtU1R3cGhnTVhBekZ1R2M4MzRnPT0="
          restartPolicy: OnFailure
